import type { Question } from "./learning";

const item = (id: string, prompt: string, choices: string[], answer: string, hint: string, explanation: string): Question => ({ id, prompt, choices, answer, hint, explanation, visual: "reading", skill: "language" });

export const grade4EnglishQuestArc: Question[] = [
  item("e4-1", "A story says: ‘Mina clutched her umbrella as dark clouds gathered.’ What is Mina most likely expecting?", ["Rain", "A birthday cake", "A football match"], "Rain", "Use the umbrella and dark clouds as clues.", "An umbrella and gathering dark clouds suggest that Mina expects rain."),
  item("e4-2", "Which word is closest in meaning to ‘enormous’?", ["Tiny", "Huge", "Silent"], "Huge", "Think of something far bigger than usual.", "Enormous means very large, or huge."),
  item("e4-3", "Choose the sentence with the clearest full stop.", ["The owl flew across the sky.", "the owl flew across the sky", "The owl flew across the sky?"], "The owl flew across the sky.", "A complete statement begins with a capital letter and ends with a full stop.", "This is a statement, so it needs a capital letter and a full stop."),
  item("e4-4", "Ravi practised the flute every day. At the concert, he played confidently. Why did he play confidently?", ["He practised every day", "He lost his flute", "The concert was cancelled"], "He practised every day", "Look for the earlier detail that explains the later result.", "Regular practice helped Ravi feel confident at the concert."),
  item("e4-5", "Which describing word makes this sentence more vivid: ‘The ___ kite rose above the trees.’", ["colourful", "yesterday", "quickly"], "colourful", "A describing word tells us more about a noun.", "Colourful describes the kite, helping the reader picture it."),
  item("e4-6", "What is the best title for a paragraph about classmates collecting litter from a park?", ["A Cleaner Park", "The Sleeping Dragon", "How to Bake Bread"], "A Cleaner Park", "A title should tell readers the main idea.", "The paragraph is about caring for a park, so ‘A Cleaner Park’ fits its main idea."),
];

export const grade5EnglishQuestArc: Question[] = [
  item("e5-1", "The paragraph says: ‘The empty playground was quiet after the rain, but one puddle reflected a bright rainbow.’ What is the mood?", ["Peaceful", "Furious", "Noisy"], "Peaceful", "Notice words such as quiet and bright.", "The quiet playground and bright rainbow create a peaceful mood."),
  item("e5-2", "Which word is the best antonym for ‘ancient’?", ["Modern", "Old", "Historic"], "Modern", "An antonym has the opposite meaning.", "Modern means current or new, the opposite of ancient."),
  item("e5-3", "Which sentence uses a comma correctly?", ["After lunch, we planted seeds.", "After, lunch we planted seeds.", "After lunch we, planted seeds."], "After lunch, we planted seeds.", "A short opening phrase can be followed by a comma.", "The comma separates the opening phrase ‘After lunch’ from the rest of the sentence."),
  item("e5-4", "Leena packed an extra sandwich before the trip because she knew a classmate had forgotten theirs. What trait does this show?", ["Kindness", "Carelessness", "Impatience"], "Kindness", "Think about how Leena’s choice affects someone else.", "Packing extra food to help a classmate shows kindness."),
  item("e5-5", "Which connective best completes: ‘The path was muddy, ___ we wore boots.’", ["so", "but", "because"], "so", "The second idea is the result of the first idea.", "The path was muddy, so wearing boots was a sensible result."),
  item("e5-6", "Which opening is best for an informative paragraph about saving water?", ["Water is precious, and small daily choices can help us save it.", "Once there was a dragon with a tap.", "My favourite colour is blue."], "Water is precious, and small daily choices can help us save it.", "An informative opening should introduce the topic clearly.", "This sentence introduces saving water and gives the reader the main idea."),
];

export const grade6EnglishQuestArc: Question[] = [
  item("e6-1", "A narrator says, ‘I kept the letter in my pocket all day, afraid to open it.’ What can you infer?", ["The letter matters to the narrator", "The narrator cannot read", "The letter is empty"], "The letter matters to the narrator", "Use the narrator’s careful, worried action as evidence.", "Keeping the letter close and fearing to open it suggests it is important to the narrator."),
  item("e6-2", "Which word best replaces ‘said’ in: ‘“We did it!” Riya ___.’", ["exclaimed", "whispered", "muttered"], "exclaimed", "The exclamation mark suggests a strong, excited voice.", "‘Exclaimed’ matches the excitement shown by ‘We did it!’"),
  item("e6-3", "Which sentence uses a semicolon correctly?", ["The rain stopped; the match began.", "The rain; stopped the match began.", "The rain stopped the; match began."], "The rain stopped; the match began.", "A semicolon can link two closely related complete statements.", "Both sides are complete statements and their ideas are closely connected."),
  item("e6-4", "Which is the strongest evidence for the claim ‘cycling can reduce traffic pollution’?", ["Bicycles do not release exhaust while being ridden", "Cycling is always faster than trains", "Every road has a cycle lane"], "Bicycles do not release exhaust while being ridden", "Choose evidence that directly supports the claim.", "The lack of exhaust from bicycles directly supports the pollution claim."),
  item("e6-5", "Which phrase creates the clearest image?", ["The moon hung like a silver lantern", "The moon was there", "Moon night thing"], "The moon hung like a silver lantern", "Look for a comparison that helps the reader picture the scene.", "The comparison to a silver lantern creates a vivid image of the moon."),
  item("e6-6", "What should a conclusion of a persuasive paragraph do?", ["Restate the main point and leave a clear final thought", "Introduce an unrelated topic", "Repeat every sentence exactly"], "Restate the main point and leave a clear final thought", "A conclusion brings an argument to a purposeful close.", "A good conclusion reinforces the main point and gives the reader a final impression."),
];

export const grade7EnglishQuestArc: Question[] = [
  item("e7-1", "A writer describes a street as ‘a river of umbrellas.’ Which device is used?", ["Metaphor", "Instruction", "Fact"], "Metaphor", "The street is compared directly to a river without using ‘like’ or ‘as’.", "Calling the street a river of umbrellas is a metaphor that creates a strong image."),
  item("e7-2", "Which source is strongest evidence for a report about local air quality?", ["A verified monitoring report", "A rumour from a friend", "An unrelated story"], "A verified monitoring report", "Choose information collected and checked for the exact topic.", "A verified monitoring report is directly relevant and more reliable evidence."),
  item("e7-3", "Which sentence uses active voice?", ["The students planted the trees.", "The trees were planted by the students.", "The trees had been being planted."], "The students planted the trees.", "In active voice, the subject performs the action.", "The students are the subject and they perform the action of planting."),
  item("e7-4", "Which phrase best signals a contrast in an argument?", ["However", "For example", "Therefore"], "However", "A contrast introduces an idea that differs from the previous one.", "‘However’ signals that the next point contrasts with what came before."),
  item("e7-5", "What is the purpose of a counterargument in persuasive writing?", ["To acknowledge and respond to another view", "To change the topic completely", "To avoid giving evidence"], "To acknowledge and respond to another view", "Strong arguments show they have considered more than one perspective.", "A counterargument addresses another view and can strengthen the writer’s position."),
  item("e7-6", "Which revision makes this sentence more precise: ‘The thing was good.’", ["The solar cooker reduced the need for firewood.", "The thing was nice.", "Good thing happened."], "The solar cooker reduced the need for firewood.", "Choose words that name the object and explain its effect.", "The revision is precise because it identifies the solar cooker and its specific benefit."),
];

export const grade8EnglishQuestArc: Question[] = [
  item("e8-1", "Which detail most strongly suggests a narrator is unreliable?", ["Their account contradicts a fact shown elsewhere", "They use a full stop", "They describe a room"], "Their account contradicts a fact shown elsewhere", "An unreliable narrator may not give a fully accurate account.", "A contradiction with established evidence gives readers reason to question the narrator’s account."),
  item("e8-2", "Which sentence uses a relative clause?", ["The book that I borrowed was inspiring.", "I borrowed the book yesterday.", "Borrow the book."], "The book that I borrowed was inspiring.", "Look for a clause that gives extra information about a noun.", "‘That I borrowed’ is a relative clause describing which book."),
  item("e8-3", "What is the main purpose of citing a source in a report?", ["To show where information came from", "To make the report longer", "To avoid reading the source"], "To show where information came from", "Good research lets readers trace important information.", "Citations acknowledge sources and let readers check the evidence."),
  item("e8-4", "Which claim is most precise?", ["The survey found that 62% of students preferred a shaded playground.", "Most people like things.", "Playgrounds are interesting."], "The survey found that 62% of students preferred a shaded playground.", "A precise claim names the evidence and the exact finding.", "This claim states both the data source and a specific result."),
  item("e8-5", "Which transition best introduces a result?", ["As a result", "In contrast", "For instance"], "As a result", "A result follows from an earlier cause or action.", "‘As a result’ clearly signals an outcome of what came before."),
  item("e8-6", "What does a strong revision usually improve first?", ["Clarity, evidence, and organisation", "Only the font size", "The number of unrelated ideas"], "Clarity, evidence, and organisation", "Revision is about making meaning stronger for the reader.", "Strong revision improves how clearly ideas are arranged and supported."),
];

export const grade9EnglishQuestArc: Question[] = [
  item("e9-1", "What is the effect of a first-person narrator?", ["It gives readers one character’s perspective", "It shows every mind equally", "It removes all viewpoint"], "It gives readers one character’s perspective", "Notice the use of ‘I’ and the limits of what that person knows.", "A first-person narrator lets readers experience events through one character’s perspective."),
  item("e9-2", "Which evidence best supports an argument about reducing food waste?", ["Data showing how much edible food is discarded", "A random slogan", "A description of a holiday"], "Data showing how much edible food is discarded", "Strong evidence directly measures the issue in the claim.", "Data about discarded edible food directly supports an argument about food waste."),
  item("e9-3", "Which sentence avoids a dangling modifier?", ["After reading the report, Maya wrote a response.", "After reading the report, a response was written.", "After reading, the report was response."], "After reading the report, Maya wrote a response.", "The person who read the report should appear directly after the opening phrase.", "Maya is clearly the person who read the report and wrote the response."),
  item("e9-4", "What should a thesis statement do in an analytical essay?", ["State the central argument or interpretation", "List every quotation", "Avoid taking a position"], "State the central argument or interpretation", "A thesis guides the reader through the essay’s main claim.", "A thesis presents the central argument that the essay will develop with evidence."),
  item("e9-5", "Which phrase signals a qualification to a claim?", ["In many cases", "Without any doubt ever", "For no reason"], "In many cases", "A qualification limits a claim so it stays accurate.", "‘In many cases’ acknowledges that a claim may not apply in every situation."),
  item("e9-6", "Why should a writer distinguish fact from opinion in a report?", ["Readers need to know what can be verified", "Opinions are always illegal", "Facts never need evidence"], "Readers need to know what can be verified", "Reports should make evidence and viewpoint clear.", "Distinguishing fact from opinion helps readers judge what is supported and what is a viewpoint."),
];

export const grade10EnglishQuestArc: Question[] = [
  item("e10-1", "What makes an interpretation of a literary text convincing?", ["Specific textual evidence and clear reasoning", "A claim with no examples", "The longest possible sentence"], "Specific textual evidence and clear reasoning", "An interpretation needs evidence from the text and an explanation of how it supports the idea.", "Specific evidence plus reasoning makes an interpretation credible and clear."),
  item("e10-2", "Which sentence is most formal for a report?", ["The findings indicate a significant increase in demand.", "Demand went totally crazy.", "Everybody knows demand was huge."], "The findings indicate a significant increase in demand.", "Formal reports use precise, neutral language.", "This sentence is precise and neutral, fitting a report’s formal tone."),
  item("e10-3", "Why should a writer address a counterclaim?", ["To show the argument has considered other reasonable views", "To avoid giving evidence", "To make the conclusion unrelated"], "To show the argument has considered other reasonable views", "A strong argument engages with possible objections.", "Addressing a counterclaim can make an argument more balanced and persuasive."),
  item("e10-4", "Which citation practice avoids plagiarism?", ["Credit the source when using its ideas or words", "Remove the author’s name", "Copy without changes"], "Credit the source when using its ideas or words", "Readers should be able to distinguish your work from a source’s ideas.", "Citing sources gives credit and makes the origin of information clear."),
  item("e10-5", "What is the purpose of a topic sentence?", ["State the main idea of a paragraph", "Repeat the title only", "Introduce a new unrelated essay"], "State the main idea of a paragraph", "A paragraph needs a clear controlling idea.", "A topic sentence tells readers the main point that the paragraph will develop."),
  item("e10-6", "Which revision strengthens cohesion between paragraphs?", ["Use clear links that show how the ideas connect", "Change every paragraph to a different topic", "Remove all transitions"], "Use clear links that show how the ideas connect", "Cohesion helps readers follow the movement of an argument.", "Clear linking language shows readers how one paragraph connects to the next."),
];

export const grade11EnglishQuestArc: Question[] = [
  item("e11-1", "What makes a research question effective?", ["It is focused, answerable, and evidence-seeking", "It has no limits", "It already contains the conclusion"], "It is focused, answerable, and evidence-seeking", "A useful research question guides what evidence you need to find.", "Focused, answerable questions make research more purposeful and manageable."),
  item("e11-2", "Why should a writer synthesise sources rather than list summaries?", ["To show how sources connect or differ around an idea", "To avoid reading them", "To use more quotations without explanation"], "To show how sources connect or differ around an idea", "Synthesis builds a relationship between sources and the writer’s claim.", "Synthesis helps readers understand how multiple sources together support, complicate, or challenge an argument."),
  item("e11-3", "Which sentence best maintains an academic register?", ["The evidence suggests a correlation, not proof of causation.", "This totally proves everything.", "The evidence is super cool."], "The evidence suggests a correlation, not proof of causation.", "Academic register is precise, cautious, and evidence-aware.", "This sentence distinguishes correlation from causation with precise, appropriate language."),
  item("e11-4", "What is a warrant in an argument?", ["The reasoning that connects evidence to a claim", "A decorative quotation", "The paper’s font"], "The reasoning that connects evidence to a claim", "A warrant explains why the evidence matters for the claim.", "A warrant makes the logical connection between evidence and the argument explicit."),
  item("e11-5", "Why is paraphrasing still cited?", ["The underlying idea came from another source", "Paraphrasing makes an idea ownerless", "Citations are only for direct quotes"], "The underlying idea came from another source", "Changing wording does not change where an idea originated.", "Paraphrases need citation because the idea or information still comes from the source."),
  item("e11-6", "Which revision best improves concision?", ["The committee rejected the proposal.", "The committee made a rejection of the proposal.", "The proposal was something that received rejection."], "The committee rejected the proposal.", "Prefer a direct verb when it says the idea clearly.", "The direct verb ‘rejected’ is clearer and more concise."),
];

export function getEnglishQuestsForGrade(grade: 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12): Question[] {
  return grade === 4 ? grade4EnglishQuestArc : grade === 5 ? grade5EnglishQuestArc : grade === 6 ? grade6EnglishQuestArc : grade === 7 ? grade7EnglishQuestArc : grade === 8 ? grade8EnglishQuestArc : grade === 9 ? grade9EnglishQuestArc : grade === 10 ? grade10EnglishQuestArc : grade === 11 ? grade11EnglishQuestArc : [];
}
