import type { Question } from "./learning";

const item = (id: string, prompt: string, choices: string[], answer: string, hint: string, explanation: string): Question => ({ id, prompt, choices, answer, hint, explanation, visual: "ecosystem", skill: "science-inquiry" });

export const grade4ScienceQuestArc: Question[] = [
  item("s4-1", "A plant is kept in sunlight but receives no water. What does it still need to grow well?", ["Water", "Only a larger pot", "A louder sound"], "Water", "Think about the basic needs of a living plant.", "Plants need water as well as light, air, and suitable conditions to grow."),
  item("s4-2", "In a simple food chain: grass → rabbit → fox, what does the rabbit eat?", ["Grass", "Fox", "Sunlight only"], "Grass", "Follow the arrow from the food to the animal that eats it.", "The rabbit eats grass; the fox can then eat the rabbit."),
  item("s4-3", "Wet clothes become dry in the sun because liquid water changes into what?", ["Water vapour", "Soil", "Ice"], "Water vapour", "Heat can change liquid water into a gas that mixes with air.", "Sunlight gives water energy to evaporate into water vapour."),
  item("s4-4", "Which animal is best adapted to a hot, dry desert?", ["Camel", "Polar bear", "Frog"], "Camel", "Think about which animal can manage heat and very little water.", "Camels have features that help them live in hot, dry deserts."),
  item("s4-5", "Which material would soak up a spill best?", ["Cotton cloth", "Glass sheet", "Steel spoon"], "Cotton cloth", "Choose a material with tiny spaces that can hold water.", "Cotton cloth is absorbent, so it can take in the spilled water."),
  item("s4-6", "Why is it important not to pour waste into a pond?", ["It can harm plants and animals living there", "It makes the pond grow taller", "It turns water into sunlight"], "It can harm plants and animals living there", "A pond is a habitat shared by many living things.", "Waste can pollute water and harm the plants, animals, and people who depend on it."),
];

export const grade5ScienceQuestArc: Question[] = [
  item("s5-1", "Which part of a plant takes in water from the soil?", ["Roots", "Flowers", "Leaves"], "Roots", "Think about the part below the ground.", "Roots absorb water and minerals from the soil."),
  item("s5-2", "Water vapour cools and forms tiny drops in clouds. What is this called?", ["Condensation", "Melting", "Freezing"], "Condensation", "A gas cools and changes back into a liquid.", "Condensation is when water vapour cools into tiny liquid water drops."),
  item("s5-3", "Which action can help prevent the spread of many germs?", ["Washing hands with soap", "Sharing an unwashed bottle", "Sneezing into the air"], "Washing hands with soap", "Germs can move from hands to food, faces, and other people.", "Washing hands with soap removes many germs and helps reduce their spread."),
  item("s5-4", "A toy car slows down when it rolls across a rough carpet. Which force causes this?", ["Friction", "Magnetism", "Gravity disappearing"], "Friction", "A rough surface resists movement between touching objects.", "Friction between the carpet and wheels slows the car down."),
  item("s5-5", "Which material is most suitable for a raincoat?", ["Waterproof fabric", "Tissue paper", "Cotton wool"], "Waterproof fabric", "A raincoat should stop water passing through.", "Waterproof fabric resists water, helping keep the wearer dry."),
  item("s5-6", "Why should a forest habitat be protected?", ["Many plants and animals depend on it", "It makes every day colder", "It stops all rivers"], "Many plants and animals depend on it", "A habitat provides food, shelter, and space for living things.", "Forests support many living things and help keep ecosystems healthy."),
];

export const grade6ScienceQuestArc: Question[] = [
  item("s6-1", "Which nutrient mainly helps the body build and repair tissues?", ["Protein", "Water", "Fibre only"], "Protein", "Think about the nutrient linked with growth and repair.", "Protein helps the body grow and repair tissues."),
  item("s6-2", "Which method separates sand from water?", ["Filtration", "Melting", "Magnetising the water"], "Filtration", "A filter lets liquid pass while trapping insoluble solid particles.", "Filtration separates insoluble sand from water."),
  item("s6-3", "Which is a reversible change?", ["Melting ice", "Burning paper", "Cooking rice"], "Melting ice", "Ask whether the original material can be made again easily.", "Melted ice can freeze back into ice, so this change is reversible."),
  item("s6-4", "A cyclist travels 24 km in 3 hours. What is the average speed?", ["8 km/h", "21 km/h", "72 km/h"], "8 km/h", "Speed = distance ÷ time.", "24 ÷ 3 = 8, so the average speed is 8 km/h."),
  item("s6-5", "Why is a shadow formed?", ["An opaque object blocks light", "Light becomes heavier", "Air turns black"], "An opaque object blocks light", "Think about what happens when light cannot pass through an object.", "A shadow forms where an opaque object blocks light from reaching a surface."),
  item("s6-6", "Why are decomposers important in an ecosystem?", ["They break down dead material and return nutrients", "They make all animals larger", "They stop plants using sunlight"], "They break down dead material and return nutrients", "Dead material does not disappear; think about what recycles it.", "Decomposers recycle nutrients by breaking down dead plants and animals."),
];

export const grade7ScienceQuestArc: Question[] = [
  item("s7-1", "Which process lets green plants make food using sunlight?", ["Photosynthesis", "Respiration only", "Filtration"], "Photosynthesis", "Think about the plant process that uses sunlight, water, and carbon dioxide.", "Photosynthesis is the process by which green plants use sunlight to make food."),
  item("s7-2", "Heat moves from a hotter cup of tea to a cooler spoon mainly by what?", ["Conduction", "Evaporation only", "Digestion"], "Conduction", "The spoon is touching the hot tea.", "Conduction transfers heat through direct contact between the tea and spoon."),
  item("s7-3", "Why is a balanced diet important?", ["It provides different nutrients the body needs", "It contains only sugar", "It removes the need for water"], "It provides different nutrients the body needs", "Different body functions need different nutrients.", "A balanced diet provides a range of nutrients for energy, growth, repair, and health."),
  item("s7-4", "In a food web, what may happen if many insects disappear?", ["Animals that eat insects may have less food", "Every animal gets more food", "Plants stop needing sunlight"], "Animals that eat insects may have less food", "Food webs connect feeding relationships.", "If insects decline, animals that depend on them for food may be affected."),
  item("s7-5", "Which mixture can be separated using evaporation?", ["Salt dissolved in water", "Iron pins and sand", "Large stones and leaves"], "Salt dissolved in water", "The water can leave as vapour, but the dissolved solid remains.", "Evaporation removes water and leaves the dissolved salt behind."),
  item("s7-6", "Why should antibiotics not be used for a common viral cold without medical advice?", ["Antibiotics do not treat viruses", "They turn viruses into plants", "They replace sleep"], "Antibiotics do not treat viruses", "Antibiotics target bacteria, not viruses.", "A cold is usually caused by a virus, so antibiotics will not treat it."),
];

export const grade8ScienceQuestArc: Question[] = [
  item("s8-1", "Why are microorganisms used to make curd?", ["They convert milk sugar into acids", "They freeze milk instantly", "They add metal to milk"], "They convert milk sugar into acids", "Think about the useful activity of bacteria in fermentation.", "Certain bacteria ferment milk sugar, producing acids that help milk set into curd."),
  item("s8-2", "Why does a sharp knife cut more easily than a blunt one with the same force?", ["It applies force over a smaller area", "It has no friction", "It weighs nothing"], "It applies force over a smaller area", "Pressure increases when the same force acts on a smaller area.", "A sharp edge concentrates force on a small area, producing greater pressure."),
  item("s8-3", "Sound cannot travel through which medium?", ["Vacuum", "Air", "Water"], "Vacuum", "Sound needs particles to pass on vibrations.", "A vacuum has no particles, so sound cannot travel through it."),
  item("s8-4", "Which structure controls the activities of a cell?", ["Nucleus", "Cell wall only", "Vacuole only"], "Nucleus", "Look for the cell part that contains genetic material and directs activities.", "The nucleus contains genetic material and controls many cell activities."),
  item("s8-5", "Why should plastic waste be reduced near wildlife habitats?", ["Animals may ingest it or become entangled", "Plastic helps every animal grow", "It turns into soil overnight"], "Animals may ingest it or become entangled", "Consider how discarded objects can harm animals directly.", "Plastic can injure wildlife through ingestion or entanglement and can persist for a long time."),
  item("s8-6", "A student wants to test whether light affects plant growth. What should stay the same between two groups?", ["Water, soil, and plant type", "The question being tested", "Only the colour of the labels"], "Water, soil, and plant type", "A fair test changes one main factor and controls the others.", "Keeping other conditions the same makes it more likely that light explains any difference."),
];

export const grade9ScienceQuestArc: Question[] = [
  item("s9-1", "Which statement best describes a physical change?", ["No new substance is formed", "Atoms disappear", "A new element is always made"], "No new substance is formed", "Think about whether the material’s chemical identity changes.", "In a physical change, the substance may change state or shape but no new substance is formed."),
  item("s9-2", "What is the SI unit of force?", ["Newton", "Joule", "Metre per second"], "Newton", "This unit is named after a scientist associated with laws of motion.", "Force is measured in newtons (N)."),
  item("s9-3", "If an object moves at constant velocity, what is its acceleration?", ["Zero", "Always increasing", "Equal to its mass"], "Zero", "Acceleration measures change in velocity.", "Constant velocity means velocity is not changing, so acceleration is zero."),
  item("s9-4", "Why does an atom have no overall charge when it is neutral?", ["It has equal numbers of protons and electrons", "It has no particles", "All neutrons are positive"], "It has equal numbers of protons and electrons", "Positive proton charge is balanced by negative electron charge.", "Equal positive and negative charges give a neutral atom no net charge."),
  item("s9-5", "Which cell organelle releases energy from food during respiration?", ["Mitochondrion", "Cell wall", "Chloroplast only"], "Mitochondrion", "This organelle is often described as the cell’s energy-release site.", "Mitochondria release usable energy from food during cellular respiration."),
  item("s9-6", "Why do scientists repeat measurements in an investigation?", ["To improve reliability and spot unusual results", "To change the hypothesis each time", "To avoid recording data"], "To improve reliability and spot unusual results", "Repeated data can reveal whether one reading was unusual.", "Repeating measurements makes evidence more reliable and helps identify anomalies."),
];

export const grade10ScienceQuestArc: Question[] = [
  item("s10-1", "Which observation best indicates a chemical reaction?", ["A gas is produced when substances are mixed", "Ice melts", "Paper is cut"], "A gas is produced when substances are mixed", "A new substance or gas can be evidence of chemical change.", "Gas production can show that a chemical reaction has formed new substances."),
  item("s10-2", "Which process releases energy from glucose in living cells?", ["Cellular respiration", "Photosynthesis", "Filtration"], "Cellular respiration", "Cells break down food molecules to release usable energy.", "Cellular respiration releases energy from glucose for cell activities."),
  item("s10-3", "In a series circuit, what happens if one bulb breaks?", ["The whole circuit stops conducting", "Other bulbs always get brighter", "Current becomes infinite"], "The whole circuit stops conducting", "A series circuit has one continuous path.", "A broken bulb opens the only path, so current cannot flow through the circuit."),
  item("s10-4", "Why is a concave mirror used in a torch?", ["It can direct light into a strong beam", "It removes all light", "It makes electricity"], "It can direct light into a strong beam", "Think about how the mirror reflects rays from a source near its focus.", "A concave mirror can reflect light outward in a more directed beam."),
  item("s10-5", "What is the role of DNA in heredity?", ["It carries genetic information", "It is only a source of heat", "It replaces every cell"], "It carries genetic information", "Traits are passed through instructions stored in cells.", "DNA carries genetic information that helps determine inherited traits."),
  item("s10-6", "Which action most directly reduces household carbon emissions?", ["Using less electricity from fossil-fuel sources", "Leaving appliances on", "Burning mixed waste"], "Using less electricity from fossil-fuel sources", "Energy use can lead to emissions when power is generated from fossil fuels.", "Reducing electricity waste can lower demand for fossil-fuel-generated power and emissions."),
];

export const grade11ScienceQuestArc: Question[] = [
  item("s11-1", "Why is a control group useful in an experiment?", ["It provides a comparison for the tested change", "It guarantees the hypothesis is true", "It removes the need for data"], "It provides a comparison for the tested change", "A control is treated the same except for the factor being tested.", "A control group helps show whether the tested variable is linked to an observed effect."),
  item("s11-2", "What does a negative slope on a velocity–time graph indicate?", ["Velocity is decreasing", "Mass is increasing", "Time is stopping"], "Velocity is decreasing", "Slope represents the rate at which velocity changes.", "A negative slope means velocity decreases with time, indicating negative acceleration in the chosen direction."),
  item("s11-3", "Why does increasing temperature often increase reaction rate?", ["Particles collide more often with enough energy", "Atoms become weightless", "Products disappear"], "Particles collide more often with enough energy", "Think about how faster-moving particles collide.", "Higher temperature increases collision frequency and the chance that collisions have sufficient energy."),
  item("s11-4", "What is the main function of an enzyme?", ["Speed up a biochemical reaction", "Store every gene", "Transport oxygen in blood"], "Speed up a biochemical reaction", "Enzymes lower the energy barrier for specific reactions.", "Enzymes act as biological catalysts, speeding up specific biochemical reactions."),
  item("s11-5", "Why should a scientific conclusion include uncertainty or limitations?", ["Evidence has boundaries and possible sources of error", "It makes the data disappear", "It means no result can be used"], "Evidence has boundaries and possible sources of error", "Good conclusions state what the data can and cannot support.", "Acknowledging limitations makes scientific claims more accurate and transparent."),
  item("s11-6", "Which is the most responsible use of a model in science?", ["Use it to explain and predict within its assumptions", "Treat it as reality in every situation", "Ignore evidence that disagrees with it"], "Use it to explain and predict within its assumptions", "Models simplify systems and have limits.", "Scientific models are useful for explanation and prediction when their assumptions and limitations are understood."),
];

export function getScienceQuestsForGrade(grade: 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12): Question[] {
  return grade === 4 ? grade4ScienceQuestArc : grade === 5 ? grade5ScienceQuestArc : grade === 6 ? grade6ScienceQuestArc : grade === 7 ? grade7ScienceQuestArc : grade === 8 ? grade8ScienceQuestArc : grade === 9 ? grade9ScienceQuestArc : grade === 10 ? grade10ScienceQuestArc : grade === 11 ? grade11ScienceQuestArc : [];
}
