import type { Question } from "./learning";

const item = (id: string, prompt: string, choices: string[], answer: string, hint: string, explanation: string): Question => ({ id, prompt, choices, answer, hint, explanation, visual: "map", skill: "social-inquiry" });

export const grade4SocialQuestArc: Question[] = [
  item("ss4-1", "On a map, which direction is usually at the top when there is a north arrow?", ["North", "South", "West"], "North", "Follow the point of the north arrow.", "Maps usually place north at the top, shown by a north arrow."),
  item("ss4-2", "You face north and turn right. Which direction are you facing?", ["East", "West", "South"], "East", "Picture the four main directions around you.", "When you face north, your right side points east."),
  item("ss4-3", "Why does a map use symbols such as a blue line for a river?", ["To show places clearly in a small space", "To hide the river", "To make every map identical"], "To show places clearly in a small space", "A map cannot draw everything full size.", "Symbols help maps show important features clearly without drawing them at real size."),
  item("ss4-4", "A neighbour uses a wheelchair. What makes a public building easier for them to enter?", ["A ramp", "A locked gate", "A very high step"], "A ramp", "Think about what lets wheels move safely from ground level to the entrance.", "A ramp helps wheelchair users enter a building more independently and safely."),
  item("ss4-5", "Which action helps save a shared resource?", ["Turning off a tap after use", "Leaving lights on all day", "Throwing litter into a drain"], "Turning off a tap after use", "Shared resources need care so everyone can use them.", "Turning off taps helps avoid wasting water, a resource people and living things need."),
  item("ss4-6", "Two classmates speak different home languages. What is a respectful response?", ["Be curious and listen", "Tell one classmate to stop speaking", "Exclude them from the game"], "Be curious and listen", "Communities can include many languages and ways of life.", "Listening with curiosity helps everyone feel included in a diverse community."),
];

export const grade5SocialQuestArc: Question[] = [
  item("ss5-1", "Which map feature helps you understand what a symbol means?", ["Key or legend", "Title only", "Page number"], "Key or legend", "Look for the part that explains map symbols.", "A map key, also called a legend, explains what each symbol represents."),
  item("ss5-2", "A scale says 1 cm on the map represents 2 km in real life. What does 3 cm represent?", ["6 km", "3 km", "5 km"], "6 km", "Each centimetre stands for 2 km; make three equal groups.", "3 × 2 km = 6 km in real life."),
  item("ss5-3", "Which is a responsibility of a community member?", ["Following shared safety rules", "Damaging public property", "Ignoring an emergency"], "Following shared safety rules", "Responsibilities help people live safely and fairly together.", "Following shared safety rules helps protect everyone in the community."),
  item("ss5-4", "Why do families and communities celebrate different festivals?", ["People have diverse traditions and beliefs", "Only one festival is allowed", "Maps choose every celebration"], "People have diverse traditions and beliefs", "India includes many communities with different customs.", "Different festivals reflect the diverse traditions and beliefs of people and communities."),
  item("ss5-5", "Which choice uses a natural resource responsibly?", ["Carrying a reusable bottle", "Wasting clean water", "Burning plastic in a park"], "Carrying a reusable bottle", "Think about choices that reduce waste and protect resources.", "A reusable bottle can reduce single-use waste and help care for shared resources."),
  item("ss5-6", "A local council wants to know whether a park needs more bins. What is a fair first step?", ["Ask park users and observe the area", "Guess without visiting", "Only ask one person"], "Ask park users and observe the area", "A fair decision uses information from the people and place involved.", "Listening to users and observing the park provides better evidence for a community decision."),
];

export const grade6SocialQuestArc: Question[] = [
  item("ss6-1", "Why do historians use more than one source to learn about the past?", ["Different sources can provide evidence and perspectives", "One source is always enough", "History has no evidence"], "Different sources can provide evidence and perspectives", "Think about how one source can be limited or incomplete.", "Comparing sources helps historians build a stronger, more balanced understanding of the past."),
  item("ss6-2", "Which tool helps show the exact direction of a place from another place?", ["Compass", "Thermometer", "Ruler only"], "Compass", "This tool is designed to identify directions such as north and east.", "A compass helps identify directions on the ground or on a map."),
  item("ss6-3", "What does a globe show especially well?", ["The Earth as a round model", "Every building at full size", "Only one country"], "The Earth as a round model", "Think about how a globe differs from a flat map.", "A globe is a round model that represents the Earth’s shape and global locations."),
  item("ss6-4", "Why are rules needed in a classroom or community?", ["They help people act safely and fairly together", "They remove everyone’s voice", "They make shared spaces unusable"], "They help people act safely and fairly together", "Consider what happens when people share a space without agreed expectations.", "Fair rules help people cooperate, stay safe, and respect one another."),
  item("ss6-5", "A farmer’s work depends on reliable rainfall. Which type of resource is rainfall?", ["Natural resource", "Human-made resource", "A map symbol only"], "Natural resource", "It comes from nature rather than being made by people.", "Rainfall is a natural resource that supports agriculture and many living systems."),
  item("ss6-6", "Which action best supports equality in a group project?", ["Give each member a meaningful chance to contribute", "Let one person do every task", "Ignore quieter group members"], "Give each member a meaningful chance to contribute", "Equality includes fair chances to participate.", "Sharing meaningful roles helps all members contribute and be respected."),
];

export const grade7SocialQuestArc: Question[] = [
  item("ss7-1", "Why do historians compare written records with archaeological evidence?", ["Each can reveal different parts of the past", "Archaeology makes records unnecessary", "Objects have no information"], "Each can reveal different parts of the past", "Different types of evidence can support or challenge one another.", "Comparing records and material evidence can produce a fuller understanding of the past."),
  item("ss7-2", "Which factor most directly affects the climate of a place?", ["Latitude", "The colour of nearby houses", "The name of the town"], "Latitude", "Think about how far a place is from the equator and the amount of sunlight it receives.", "Latitude affects the angle and intensity of sunlight, influencing climate."),
  item("ss7-3", "What is a renewable resource?", ["A resource that can be naturally replenished", "A resource that can never be used", "Only a manufactured product"], "A resource that can be naturally replenished", "Think of resources that nature can restore over time when used carefully.", "Renewable resources can be replenished naturally, such as sunlight or wind."),
  item("ss7-4", "Why is public participation valuable in local decisions?", ["People can share needs and evidence about their community", "Only experts live in communities", "It guarantees every person gets the same opinion"], "People can share needs and evidence about their community", "Residents often know how a decision affects daily life.", "Public participation brings local knowledge and different perspectives into decisions."),
  item("ss7-5", "Which situation is an example of equality before the law?", ["The same legal rules apply to all people", "Rules depend only on wealth", "Some people never need to follow rules"], "The same legal rules apply to all people", "Equality means the law should not favour people because of identity or status.", "Equality before the law means the same legal standards apply to everyone."),
  item("ss7-6", "A shopkeeper compares the cost of two suppliers before buying stock. This is an example of what?", ["Making an economic choice with limited resources", "Changing the weather", "Drawing a political boundary"], "Making an economic choice with limited resources", "The shopkeeper must choose how to use money and supplies.", "Comparing costs is an economic decision about using limited resources wisely."),
];

export const grade8SocialQuestArc: Question[] = [
  item("ss8-1", "Why did historians study colonial records alongside local accounts?", ["Sources can reflect different viewpoints and interests", "All records are identical", "Local accounts have no evidence"], "Sources can reflect different viewpoints and interests", "Consider who created a source and whose perspective may be missing.", "Comparing sources helps reveal different viewpoints and possible bias in historical accounts."),
  item("ss8-2", "What is a key purpose of a constitution?", ["It sets fundamental rules and rights for governing a country", "It predicts daily weather", "It replaces all local decisions"], "It sets fundamental rules and rights for governing a country", "Think about the document that establishes how power and rights are organised.", "A constitution provides a framework for government, rights, and the rule of law."),
  item("ss8-3", "Why can overuse of groundwater create problems?", ["Water may be taken faster than it is replenished", "Groundwater becomes unlimited", "Rainfall stops forever"], "Water may be taken faster than it is replenished", "Groundwater needs time and conditions to recharge.", "Overuse can lower water levels when extraction exceeds natural recharge."),
  item("ss8-4", "Which action is an example of public accountability?", ["Officials explain how public money was used", "Decisions are hidden from everyone", "Only rumours are shared"], "Officials explain how public money was used", "Accountability means those with power answer for their decisions.", "Explaining public spending allows people to question and evaluate official decisions."),
  item("ss8-5", "Why do industries often develop near transport routes?", ["Materials and goods can move more easily", "Transport prevents all work", "Routes make resources disappear"], "Materials and goods can move more easily", "Industries need to receive materials and send products to markets.", "Transport links reduce the difficulty and cost of moving inputs and goods."),
  item("ss8-6", "A policy benefits one group but harms another. What is a fair first question?", ["Who is affected and what evidence supports the policy?", "Can we ignore the harmed group?", "Which slogan is shortest?"], "Who is affected and what evidence supports the policy?", "Fair civic reasoning considers impacts and evidence.", "Asking who is affected and examining evidence helps assess whether a policy is fair."),
];

export function getSocialQuestsForGrade(grade: 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12): Question[] {
  return grade === 4 ? grade4SocialQuestArc : grade === 5 ? grade5SocialQuestArc : grade === 6 ? grade6SocialQuestArc : grade === 7 ? grade7SocialQuestArc : grade === 8 ? grade8SocialQuestArc : [];
}
